// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_logs (id, event_type, user_id, ip_address, user_agent, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateAuditLogParams struct {
	ID        uuid.UUID             `json:"id"`
	EventType string                `json:"event_type"`
	UserID    uuid.NullUUID         `json:"user_id"`
	IpAddress sql.NullString        `json:"ip_address"`
	UserAgent sql.NullString        `json:"user_agent"`
	Metadata  pqtype.NullRawMessage `json:"metadata"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, createAuditLog,
		arg.ID,
		arg.EventType,
		arg.UserID,
		arg.IpAddress,
		arg.UserAgent,
		arg.Metadata,
	)
	return err
}
