// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_change_requests.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createEmailChangeRequest = `-- name: CreateEmailChangeRequest :one
INSERT INTO email_change_requests (
    user_id,
    new_email,
    token_hash,
    expires_at
) VALUES ($1, $2, $3, $4)
RETURNING id, user_id, new_email, token_hash, expires_at, created_at
`

type CreateEmailChangeRequestParams struct {
	UserID    uuid.UUID `json:"user_id"`
	NewEmail  string    `json:"new_email"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateEmailChangeRequest(ctx context.Context, arg CreateEmailChangeRequestParams) (EmailChangeRequest, error) {
	row := q.db.QueryRowContext(ctx, createEmailChangeRequest,
		arg.UserID,
		arg.NewEmail,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i EmailChangeRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NewEmail,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEmailChangeRequest = `-- name: DeleteEmailChangeRequest :exec
DELETE FROM email_change_requests WHERE id = $1
`

func (q *Queries) DeleteEmailChangeRequest(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteEmailChangeRequest, id)
	return err
}

const deleteEmailChangeRequestsByUserID = `-- name: DeleteEmailChangeRequestsByUserID :exec
DELETE FROM email_change_requests WHERE user_id = $1
`

func (q *Queries) DeleteEmailChangeRequestsByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteEmailChangeRequestsByUserID, userID)
	return err
}

const findValidEmailChangeRequestByTokenHash = `-- name: FindValidEmailChangeRequestByTokenHash :one
SELECT id, user_id, new_email, token_hash, expires_at, created_at
FROM email_change_requests
WHERE token_hash = $1 AND expires_at > NOW()
`

func (q *Queries) FindValidEmailChangeRequestByTokenHash(ctx context.Context, tokenHash string) (EmailChangeRequest, error) {
	row := q.db.QueryRowContext(ctx, findValidEmailChangeRequestByTokenHash, tokenHash)
	var i EmailChangeRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NewEmail,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingEmailChangeRequestByUserID = `-- name: GetPendingEmailChangeRequestByUserID :one
SELECT id, user_id, new_email, token_hash, expires_at, created_at
FROM email_change_requests
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetPendingEmailChangeRequestByUserID(ctx context.Context, userID uuid.UUID) (EmailChangeRequest, error) {
	row := q.db.QueryRowContext(ctx, getPendingEmailChangeRequestByUserID, userID)
	var i EmailChangeRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NewEmail,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
