// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_verification_tokens.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countEmailVerificationTokensCreatedToday = `-- name: CountEmailVerificationTokensCreatedToday :one
SELECT COUNT(*)
FROM email_verification_tokens
WHERE user_id = $1 AND created_at > (NOW() - INTERVAL '24 hours')
`

func (q *Queries) CountEmailVerificationTokensCreatedToday(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEmailVerificationTokensCreatedToday, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEmailVerificationToken = `-- name: CreateEmailVerificationToken :one
INSERT INTO email_verification_tokens (
    id,
    user_id,
    token_hash,
    expires_at
) VALUES ($1, $2, $3, $4)
RETURNING id, user_id, token_hash, created_at, expires_at
`

type CreateEmailVerificationTokenParams struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) (EmailVerificationToken, error) {
	row := q.db.QueryRowContext(ctx, createEmailVerificationToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteAllEmailVerificationTokensForUser = `-- name: DeleteAllEmailVerificationTokensForUser :exec
DELETE FROM email_verification_tokens
WHERE user_id = $1
`

func (q *Queries) DeleteAllEmailVerificationTokensForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAllEmailVerificationTokensForUser, userID)
	return err
}

const deleteEmailVerificationToken = `-- name: DeleteEmailVerificationToken :exec
DELETE FROM email_verification_tokens
WHERE id = $1
`

func (q *Queries) DeleteEmailVerificationToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteEmailVerificationToken, id)
	return err
}

const findValidEmailVerificationToken = `-- name: FindValidEmailVerificationToken :one
SELECT id, user_id, token_hash, created_at, expires_at
FROM email_verification_tokens
WHERE token_hash = $1 AND expires_at > NOW()
`

func (q *Queries) FindValidEmailVerificationToken(ctx context.Context, tokenHash string) (EmailVerificationToken, error) {
	row := q.db.QueryRowContext(ctx, findValidEmailVerificationToken, tokenHash)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
