// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guest_access_tokens.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createGuestAccessToken = `-- name: CreateGuestAccessToken :one

INSERT INTO guest_access_tokens (
    profile_id,
    token_hash,
    label,
    permissions,
    expires_at
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, profile_id, token_hash, label, permissions, expires_at, created_at, last_used_at
`

type CreateGuestAccessTokenParams struct {
	ProfileID   uuid.UUID       `json:"profile_id"`
	TokenHash   string          `json:"token_hash"`
	Label       sql.NullString  `json:"label"`
	Permissions json.RawMessage `json:"permissions"`
	ExpiresAt   time.Time       `json:"expires_at"`
}

// Guest access token queries
func (q *Queries) CreateGuestAccessToken(ctx context.Context, arg CreateGuestAccessTokenParams) (GuestAccessToken, error) {
	row := q.db.QueryRowContext(ctx, createGuestAccessToken,
		arg.ProfileID,
		arg.TokenHash,
		arg.Label,
		arg.Permissions,
		arg.ExpiresAt,
	)
	var i GuestAccessToken
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.TokenHash,
		&i.Label,
		&i.Permissions,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const deleteGuestAccessToken = `-- name: DeleteGuestAccessToken :exec
DELETE FROM guest_access_tokens WHERE id = $1
`

func (q *Queries) DeleteGuestAccessToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteGuestAccessToken, id)
	return err
}

const deleteGuestAccessTokensByProfile = `-- name: DeleteGuestAccessTokensByProfile :exec
DELETE FROM guest_access_tokens WHERE profile_id = $1
`

func (q *Queries) DeleteGuestAccessTokensByProfile(ctx context.Context, profileID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteGuestAccessTokensByProfile, profileID)
	return err
}

const getGuestAccessTokenByHash = `-- name: GetGuestAccessTokenByHash :one
SELECT id, profile_id, token_hash, label, permissions, expires_at, created_at, last_used_at
FROM guest_access_tokens
WHERE token_hash = $1
`

func (q *Queries) GetGuestAccessTokenByHash(ctx context.Context, tokenHash string) (GuestAccessToken, error) {
	row := q.db.QueryRowContext(ctx, getGuestAccessTokenByHash, tokenHash)
	var i GuestAccessToken
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.TokenHash,
		&i.Label,
		&i.Permissions,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getGuestAccessTokenByID = `-- name: GetGuestAccessTokenByID :one
SELECT id, profile_id, token_hash, label, permissions, expires_at, created_at, last_used_at
FROM guest_access_tokens
WHERE id = $1
`

func (q *Queries) GetGuestAccessTokenByID(ctx context.Context, id uuid.UUID) (GuestAccessToken, error) {
	row := q.db.QueryRowContext(ctx, getGuestAccessTokenByID, id)
	var i GuestAccessToken
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.TokenHash,
		&i.Label,
		&i.Permissions,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const listGuestAccessTokensByProfile = `-- name: ListGuestAccessTokensByProfile :many
SELECT id, profile_id, token_hash, label, permissions, expires_at, created_at, last_used_at
FROM guest_access_tokens
WHERE profile_id = $1 AND expires_at > NOW()
ORDER BY created_at DESC
`

func (q *Queries) ListGuestAccessTokensByProfile(ctx context.Context, profileID uuid.UUID) ([]GuestAccessToken, error) {
	rows, err := q.db.QueryContext(ctx, listGuestAccessTokensByProfile, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GuestAccessToken{}
	for rows.Next() {
		var i GuestAccessToken
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.TokenHash,
			&i.Label,
			&i.Permissions,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGuestAccessTokenLastUsedAt = `-- name: UpdateGuestAccessTokenLastUsedAt :exec
UPDATE guest_access_tokens
SET last_used_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateGuestAccessTokenLastUsedAt(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateGuestAccessTokenLastUsedAt, id)
	return err
}
