// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type AuditLog struct {
	ID        uuid.UUID             `json:"id"`
	EventType string                `json:"event_type"`
	UserID    uuid.NullUUID         `json:"user_id"`
	IpAddress sql.NullString        `json:"ip_address"`
	UserAgent sql.NullString        `json:"user_agent"`
	Metadata  pqtype.NullRawMessage `json:"metadata"`
	CreatedAt sql.NullTime          `json:"created_at"`
}

type DoseSchedule struct {
	ID        uuid.UUID `json:"id"`
	ProfileID uuid.UUID `json:"profile_id"`
	Name      string    `json:"name"`
	Time      time.Time `json:"time"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type EmailChangeRequest struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	NewEmail  string       `json:"new_email"`
	TokenHash string       `json:"token_hash"`
	ExpiresAt time.Time    `json:"expires_at"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type EmailVerificationToken struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	TokenHash string       `json:"token_hash"`
	CreatedAt sql.NullTime `json:"created_at"`
	ExpiresAt time.Time    `json:"expires_at"`
}

type OauthAccount struct {
	ID             uuid.UUID    `json:"id"`
	UserID         uuid.UUID    `json:"user_id"`
	Provider       string       `json:"provider"`
	ProviderUserID string       `json:"provider_user_id"`
	CreatedAt      sql.NullTime `json:"created_at"`
}

type OauthAuthorizationCode struct {
	ID                    uuid.UUID     `json:"id"`
	CodeHash              string        `json:"code_hash"`
	UserID                uuid.NullUUID `json:"user_id"`
	Nonce                 string        `json:"nonce"`
	Purpose               string        `json:"purpose"`
	ExpiresAt             time.Time     `json:"expires_at"`
	UsedAt                sql.NullTime  `json:"used_at"`
	CreatedAt             sql.NullTime  `json:"created_at"`
	Provider              string        `json:"provider"`
	ProviderUserID        string        `json:"provider_user_id"`
	ProviderEmail         string        `json:"provider_email"`
	ProviderName          string        `json:"provider_name"`
	ProviderEmailVerified bool          `json:"provider_email_verified"`
}

type OwnershipTransfer struct {
	ID         uuid.UUID `json:"id"`
	ProfileID  uuid.UUID `json:"profile_id"`
	FromUserID uuid.UUID `json:"from_user_id"`
	ToUserID   uuid.UUID `json:"to_user_id"`
	Status     string    `json:"status"`
	ExpiresAt  time.Time `json:"expires_at"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type PasswordResetToken struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	TokenHash string       `json:"token_hash"`
	ExpiresAt time.Time    `json:"expires_at"`
	UsedAt    sql.NullTime `json:"used_at"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Profile struct {
	ID          uuid.UUID    `json:"id"`
	Name        string       `json:"name"`
	DateOfBirth sql.NullTime `json:"date_of_birth"`
	Timezone    string       `json:"timezone"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
}

type ProfilePermission struct {
	ID               uuid.UUID       `json:"id"`
	ProfileID        uuid.UUID       `json:"profile_id"`
	SharedWithUserID uuid.UUID       `json:"shared_with_user_id"`
	GrantedByUserID  uuid.UUID       `json:"granted_by_user_id"`
	Permissions      json.RawMessage `json:"permissions"`
	Status           string          `json:"status"`
	ExpiresAt        sql.NullTime    `json:"expires_at"`
	CreatedAt        time.Time       `json:"created_at"`
	UpdatedAt        time.Time       `json:"updated_at"`
}

type RefreshToken struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	TokenHash string       `json:"token_hash"`
	ExpiresAt time.Time    `json:"expires_at"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type SchemaMigration struct {
	Version   int64     `json:"version"`
	Dirty     bool      `json:"dirty"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID            uuid.UUID      `json:"id"`
	Email         string         `json:"email"`
	DisplayName   string         `json:"display_name"`
	PasswordHash  sql.NullString `json:"password_hash"`
	EmailVerified sql.NullBool   `json:"email_verified"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}
