// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth_accounts.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createOAuthAccount = `-- name: CreateOAuthAccount :one
INSERT INTO oauth_accounts (id, user_id, provider, provider_user_id, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, provider, provider_user_id, created_at
`

type CreateOAuthAccountParams struct {
	ID             uuid.UUID    `json:"id"`
	UserID         uuid.UUID    `json:"user_id"`
	Provider       string       `json:"provider"`
	ProviderUserID string       `json:"provider_user_id"`
	CreatedAt      sql.NullTime `json:"created_at"`
}

func (q *Queries) CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) (OauthAccount, error) {
	row := q.db.QueryRowContext(ctx, createOAuthAccount,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.CreatedAt,
	)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOAuthAccount = `-- name: DeleteOAuthAccount :one
DELETE FROM oauth_accounts
WHERE id = $1
RETURNING id, user_id, provider, provider_user_id, created_at
`

func (q *Queries) DeleteOAuthAccount(ctx context.Context, id uuid.UUID) (OauthAccount, error) {
	row := q.db.QueryRowContext(ctx, deleteOAuthAccount, id)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOAuthAccountByUserIDAndProvider = `-- name: DeleteOAuthAccountByUserIDAndProvider :exec
DELETE FROM oauth_accounts
WHERE user_id = $1 AND provider = $2
`

type DeleteOAuthAccountByUserIDAndProviderParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Provider string    `json:"provider"`
}

func (q *Queries) DeleteOAuthAccountByUserIDAndProvider(ctx context.Context, arg DeleteOAuthAccountByUserIDAndProviderParams) error {
	_, err := q.db.ExecContext(ctx, deleteOAuthAccountByUserIDAndProvider, arg.UserID, arg.Provider)
	return err
}

const getOAuthAccountByProviderAndUserID = `-- name: GetOAuthAccountByProviderAndUserID :one
SELECT id, user_id, provider, provider_user_id, created_at FROM oauth_accounts
WHERE provider = $1 AND provider_user_id = $2
`

type GetOAuthAccountByProviderAndUserIDParams struct {
	Provider       string `json:"provider"`
	ProviderUserID string `json:"provider_user_id"`
}

func (q *Queries) GetOAuthAccountByProviderAndUserID(ctx context.Context, arg GetOAuthAccountByProviderAndUserIDParams) (OauthAccount, error) {
	row := q.db.QueryRowContext(ctx, getOAuthAccountByProviderAndUserID, arg.Provider, arg.ProviderUserID)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
	)
	return i, err
}

const getOAuthAccountByUserIDAndProvider = `-- name: GetOAuthAccountByUserIDAndProvider :one
SELECT id, user_id, provider, provider_user_id, created_at FROM oauth_accounts
WHERE user_id = $1 AND provider = $2
`

type GetOAuthAccountByUserIDAndProviderParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Provider string    `json:"provider"`
}

func (q *Queries) GetOAuthAccountByUserIDAndProvider(ctx context.Context, arg GetOAuthAccountByUserIDAndProviderParams) (OauthAccount, error) {
	row := q.db.QueryRowContext(ctx, getOAuthAccountByUserIDAndProvider, arg.UserID, arg.Provider)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
	)
	return i, err
}

const getOAuthAccountsByUserID = `-- name: GetOAuthAccountsByUserID :many
SELECT id, user_id, provider, provider_user_id, created_at FROM oauth_accounts
WHERE user_id = $1
`

func (q *Queries) GetOAuthAccountsByUserID(ctx context.Context, userID uuid.UUID) ([]OauthAccount, error) {
	rows, err := q.db.QueryContext(ctx, getOAuthAccountsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OauthAccount{}
	for rows.Next() {
		var i OauthAccount
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
