// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth_authorization_codes.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createAuthorizationCode = `-- name: CreateAuthorizationCode :one
INSERT INTO oauth_authorization_codes (id, code_hash, user_id, nonce, purpose, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, code_hash, user_id, nonce, purpose, expires_at, used_at, created_at, provider, provider_user_id, provider_email, provider_name, provider_email_verified
`

type CreateAuthorizationCodeParams struct {
	ID        uuid.UUID     `json:"id"`
	CodeHash  string        `json:"code_hash"`
	UserID    uuid.NullUUID `json:"user_id"`
	Nonce     string        `json:"nonce"`
	Purpose   string        `json:"purpose"`
	ExpiresAt time.Time     `json:"expires_at"`
	CreatedAt sql.NullTime  `json:"created_at"`
}

func (q *Queries) CreateAuthorizationCode(ctx context.Context, arg CreateAuthorizationCodeParams) (OauthAuthorizationCode, error) {
	row := q.db.QueryRowContext(ctx, createAuthorizationCode,
		arg.ID,
		arg.CodeHash,
		arg.UserID,
		arg.Nonce,
		arg.Purpose,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	var i OauthAuthorizationCode
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.UserID,
		&i.Nonce,
		&i.Purpose,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
		&i.Provider,
		&i.ProviderUserID,
		&i.ProviderEmail,
		&i.ProviderName,
		&i.ProviderEmailVerified,
	)
	return i, err
}

const deleteAuthorizationCode = `-- name: DeleteAuthorizationCode :one
DELETE FROM oauth_authorization_codes
WHERE id = $1
RETURNING id, code_hash, user_id, nonce, purpose, expires_at, used_at, created_at, provider, provider_user_id, provider_email, provider_name, provider_email_verified
`

func (q *Queries) DeleteAuthorizationCode(ctx context.Context, id uuid.UUID) (OauthAuthorizationCode, error) {
	row := q.db.QueryRowContext(ctx, deleteAuthorizationCode, id)
	var i OauthAuthorizationCode
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.UserID,
		&i.Nonce,
		&i.Purpose,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
		&i.Provider,
		&i.ProviderUserID,
		&i.ProviderEmail,
		&i.ProviderName,
		&i.ProviderEmailVerified,
	)
	return i, err
}

const deleteExpiredAuthorizationCodes = `-- name: DeleteExpiredAuthorizationCodes :many
DELETE FROM oauth_authorization_codes
WHERE expires_at < $1
RETURNING id, code_hash, user_id, nonce, purpose, expires_at, used_at, created_at, provider, provider_user_id, provider_email, provider_name, provider_email_verified
`

func (q *Queries) DeleteExpiredAuthorizationCodes(ctx context.Context, expiresAt time.Time) ([]OauthAuthorizationCode, error) {
	rows, err := q.db.QueryContext(ctx, deleteExpiredAuthorizationCodes, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OauthAuthorizationCode{}
	for rows.Next() {
		var i OauthAuthorizationCode
		if err := rows.Scan(
			&i.ID,
			&i.CodeHash,
			&i.UserID,
			&i.Nonce,
			&i.Purpose,
			&i.ExpiresAt,
			&i.UsedAt,
			&i.CreatedAt,
			&i.Provider,
			&i.ProviderUserID,
			&i.ProviderEmail,
			&i.ProviderName,
			&i.ProviderEmailVerified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuthorizationCodeByHash = `-- name: GetAuthorizationCodeByHash :one
SELECT id, code_hash, user_id, nonce, purpose, expires_at, used_at, created_at, provider, provider_user_id, provider_email, provider_name, provider_email_verified FROM oauth_authorization_codes
WHERE code_hash = $1
`

func (q *Queries) GetAuthorizationCodeByHash(ctx context.Context, codeHash string) (OauthAuthorizationCode, error) {
	row := q.db.QueryRowContext(ctx, getAuthorizationCodeByHash, codeHash)
	var i OauthAuthorizationCode
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.UserID,
		&i.Nonce,
		&i.Purpose,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
		&i.Provider,
		&i.ProviderUserID,
		&i.ProviderEmail,
		&i.ProviderName,
		&i.ProviderEmailVerified,
	)
	return i, err
}

const getAuthorizationCodeByNonceAndPurpose = `-- name: GetAuthorizationCodeByNonceAndPurpose :one
SELECT id, code_hash, user_id, nonce, purpose, expires_at, used_at, created_at, provider, provider_user_id, provider_email, provider_name, provider_email_verified FROM oauth_authorization_codes
WHERE nonce = $1 AND purpose = $2
`

type GetAuthorizationCodeByNonceAndPurposeParams struct {
	Nonce   string `json:"nonce"`
	Purpose string `json:"purpose"`
}

func (q *Queries) GetAuthorizationCodeByNonceAndPurpose(ctx context.Context, arg GetAuthorizationCodeByNonceAndPurposeParams) (OauthAuthorizationCode, error) {
	row := q.db.QueryRowContext(ctx, getAuthorizationCodeByNonceAndPurpose, arg.Nonce, arg.Purpose)
	var i OauthAuthorizationCode
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.UserID,
		&i.Nonce,
		&i.Purpose,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
		&i.Provider,
		&i.ProviderUserID,
		&i.ProviderEmail,
		&i.ProviderName,
		&i.ProviderEmailVerified,
	)
	return i, err
}

const markAuthorizationCodeAsUsed = `-- name: MarkAuthorizationCodeAsUsed :one
UPDATE oauth_authorization_codes
SET used_at = NOW()
WHERE code_hash = $1 AND used_at IS NULL
RETURNING id, code_hash, user_id, nonce, purpose, expires_at, used_at, created_at, provider, provider_user_id, provider_email, provider_name, provider_email_verified
`

func (q *Queries) MarkAuthorizationCodeAsUsed(ctx context.Context, codeHash string) (OauthAuthorizationCode, error) {
	row := q.db.QueryRowContext(ctx, markAuthorizationCodeAsUsed, codeHash)
	var i OauthAuthorizationCode
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.UserID,
		&i.Nonce,
		&i.Purpose,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
		&i.Provider,
		&i.ProviderUserID,
		&i.ProviderEmail,
		&i.ProviderName,
		&i.ProviderEmailVerified,
	)
	return i, err
}
