// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ownership_transfers.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createOwnershipTransfer = `-- name: CreateOwnershipTransfer :one

INSERT INTO ownership_transfers (
    profile_id,
    from_user_id,
    to_user_id,
    status,
    expires_at
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, profile_id, from_user_id, to_user_id, status, expires_at, created_at, updated_at
`

type CreateOwnershipTransferParams struct {
	ProfileID  uuid.UUID `json:"profile_id"`
	FromUserID uuid.UUID `json:"from_user_id"`
	ToUserID   uuid.UUID `json:"to_user_id"`
	Status     string    `json:"status"`
	ExpiresAt  time.Time `json:"expires_at"`
}

// Ownership transfer queries
func (q *Queries) CreateOwnershipTransfer(ctx context.Context, arg CreateOwnershipTransferParams) (OwnershipTransfer, error) {
	row := q.db.QueryRowContext(ctx, createOwnershipTransfer,
		arg.ProfileID,
		arg.FromUserID,
		arg.ToUserID,
		arg.Status,
		arg.ExpiresAt,
	)
	var i OwnershipTransfer
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.FromUserID,
		&i.ToUserID,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOwnershipTransferByID = `-- name: GetOwnershipTransferByID :one
SELECT id, profile_id, from_user_id, to_user_id, status, expires_at, created_at, updated_at
FROM ownership_transfers
WHERE id = $1
`

func (q *Queries) GetOwnershipTransferByID(ctx context.Context, id uuid.UUID) (OwnershipTransfer, error) {
	row := q.db.QueryRowContext(ctx, getOwnershipTransferByID, id)
	var i OwnershipTransfer
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.FromUserID,
		&i.ToUserID,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingTransferByProfile = `-- name: GetPendingTransferByProfile :one
SELECT id, profile_id, from_user_id, to_user_id, status, expires_at, created_at, updated_at
FROM ownership_transfers
WHERE profile_id = $1 AND status = 'pending'
`

func (q *Queries) GetPendingTransferByProfile(ctx context.Context, profileID uuid.UUID) (OwnershipTransfer, error) {
	row := q.db.QueryRowContext(ctx, getPendingTransferByProfile, profileID)
	var i OwnershipTransfer
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.FromUserID,
		&i.ToUserID,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingTransfersByUser = `-- name: ListPendingTransfersByUser :many
SELECT id, profile_id, from_user_id, to_user_id, status, expires_at, created_at, updated_at
FROM ownership_transfers
WHERE to_user_id = $1 AND status = 'pending' AND expires_at > NOW()
`

func (q *Queries) ListPendingTransfersByUser(ctx context.Context, toUserID uuid.UUID) ([]OwnershipTransfer, error) {
	rows, err := q.db.QueryContext(ctx, listPendingTransfersByUser, toUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OwnershipTransfer{}
	for rows.Next() {
		var i OwnershipTransfer
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.FromUserID,
			&i.ToUserID,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOwnershipTransferStatus = `-- name: UpdateOwnershipTransferStatus :one
UPDATE ownership_transfers
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, profile_id, from_user_id, to_user_id, status, expires_at, created_at, updated_at
`

type UpdateOwnershipTransferStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateOwnershipTransferStatus(ctx context.Context, arg UpdateOwnershipTransferStatusParams) (OwnershipTransfer, error) {
	row := q.db.QueryRowContext(ctx, updateOwnershipTransferStatus, arg.ID, arg.Status)
	var i OwnershipTransfer
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.FromUserID,
		&i.ToUserID,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
