// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profile_permissions.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const acceptProfilePermission = `-- name: AcceptProfilePermission :one
UPDATE profile_permissions
SET status = 'accepted', expires_at = NULL, updated_at = NOW()
WHERE id = $1
RETURNING id, profile_id, shared_with_user_id, granted_by_user_id, permissions, status, expires_at, created_at, updated_at
`

func (q *Queries) AcceptProfilePermission(ctx context.Context, id uuid.UUID) (ProfilePermission, error) {
	row := q.db.QueryRowContext(ctx, acceptProfilePermission, id)
	var i ProfilePermission
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.SharedWithUserID,
		&i.GrantedByUserID,
		&i.Permissions,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProfilePermission = `-- name: CreateProfilePermission :one

INSERT INTO profile_permissions (
    profile_id,
    shared_with_user_id,
    granted_by_user_id,
    permissions,
    status,
    expires_at
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, profile_id, shared_with_user_id, granted_by_user_id, permissions, status, expires_at, created_at, updated_at
`

type CreateProfilePermissionParams struct {
	ProfileID        uuid.UUID       `json:"profile_id"`
	SharedWithUserID uuid.UUID       `json:"shared_with_user_id"`
	GrantedByUserID  uuid.UUID       `json:"granted_by_user_id"`
	Permissions      json.RawMessage `json:"permissions"`
	Status           string          `json:"status"`
	ExpiresAt        sql.NullTime    `json:"expires_at"`
}

// Profile permission queries
func (q *Queries) CreateProfilePermission(ctx context.Context, arg CreateProfilePermissionParams) (ProfilePermission, error) {
	row := q.db.QueryRowContext(ctx, createProfilePermission,
		arg.ProfileID,
		arg.SharedWithUserID,
		arg.GrantedByUserID,
		arg.Permissions,
		arg.Status,
		arg.ExpiresAt,
	)
	var i ProfilePermission
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.SharedWithUserID,
		&i.GrantedByUserID,
		&i.Permissions,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProfilePermission = `-- name: DeleteProfilePermission :exec
DELETE FROM profile_permissions WHERE id = $1
`

func (q *Queries) DeleteProfilePermission(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProfilePermission, id)
	return err
}

const getProfilePermission = `-- name: GetProfilePermission :one
SELECT id, profile_id, shared_with_user_id, granted_by_user_id, permissions, status, expires_at, created_at, updated_at
FROM profile_permissions
WHERE profile_id = $1 AND shared_with_user_id = $2
`

type GetProfilePermissionParams struct {
	ProfileID        uuid.UUID `json:"profile_id"`
	SharedWithUserID uuid.UUID `json:"shared_with_user_id"`
}

func (q *Queries) GetProfilePermission(ctx context.Context, arg GetProfilePermissionParams) (ProfilePermission, error) {
	row := q.db.QueryRowContext(ctx, getProfilePermission, arg.ProfileID, arg.SharedWithUserID)
	var i ProfilePermission
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.SharedWithUserID,
		&i.GrantedByUserID,
		&i.Permissions,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfilePermissionByID = `-- name: GetProfilePermissionByID :one
SELECT id, profile_id, shared_with_user_id, granted_by_user_id, permissions, status, expires_at, created_at, updated_at
FROM profile_permissions
WHERE id = $1
`

func (q *Queries) GetProfilePermissionByID(ctx context.Context, id uuid.UUID) (ProfilePermission, error) {
	row := q.db.QueryRowContext(ctx, getProfilePermissionByID, id)
	var i ProfilePermission
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.SharedWithUserID,
		&i.GrantedByUserID,
		&i.Permissions,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProfilePermissionsByProfile = `-- name: ListProfilePermissionsByProfile :many
SELECT id, profile_id, shared_with_user_id, granted_by_user_id, permissions, status, expires_at, created_at, updated_at
FROM profile_permissions
WHERE profile_id = $1
`

func (q *Queries) ListProfilePermissionsByProfile(ctx context.Context, profileID uuid.UUID) ([]ProfilePermission, error) {
	rows, err := q.db.QueryContext(ctx, listProfilePermissionsByProfile, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProfilePermission{}
	for rows.Next() {
		var i ProfilePermission
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.SharedWithUserID,
			&i.GrantedByUserID,
			&i.Permissions,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfilePermissionsByUser = `-- name: ListProfilePermissionsByUser :many
SELECT id, profile_id, shared_with_user_id, granted_by_user_id, permissions, status, expires_at, created_at, updated_at
FROM profile_permissions
WHERE shared_with_user_id = $1
`

func (q *Queries) ListProfilePermissionsByUser(ctx context.Context, sharedWithUserID uuid.UUID) ([]ProfilePermission, error) {
	rows, err := q.db.QueryContext(ctx, listProfilePermissionsByUser, sharedWithUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProfilePermission{}
	for rows.Next() {
		var i ProfilePermission
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.SharedWithUserID,
			&i.GrantedByUserID,
			&i.Permissions,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProfilePermissionExpiresAt = `-- name: UpdateProfilePermissionExpiresAt :one
UPDATE profile_permissions
SET expires_at = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, profile_id, shared_with_user_id, granted_by_user_id, permissions, status, expires_at, created_at, updated_at
`

type UpdateProfilePermissionExpiresAtParams struct {
	ID        uuid.UUID    `json:"id"`
	ExpiresAt sql.NullTime `json:"expires_at"`
}

func (q *Queries) UpdateProfilePermissionExpiresAt(ctx context.Context, arg UpdateProfilePermissionExpiresAtParams) (ProfilePermission, error) {
	row := q.db.QueryRowContext(ctx, updateProfilePermissionExpiresAt, arg.ID, arg.ExpiresAt)
	var i ProfilePermission
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.SharedWithUserID,
		&i.GrantedByUserID,
		&i.Permissions,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProfilePermissionPermissions = `-- name: UpdateProfilePermissionPermissions :one
UPDATE profile_permissions
SET permissions = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, profile_id, shared_with_user_id, granted_by_user_id, permissions, status, expires_at, created_at, updated_at
`

type UpdateProfilePermissionPermissionsParams struct {
	ID          uuid.UUID       `json:"id"`
	Permissions json.RawMessage `json:"permissions"`
}

func (q *Queries) UpdateProfilePermissionPermissions(ctx context.Context, arg UpdateProfilePermissionPermissionsParams) (ProfilePermission, error) {
	row := q.db.QueryRowContext(ctx, updateProfilePermissionPermissions, arg.ID, arg.Permissions)
	var i ProfilePermission
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.SharedWithUserID,
		&i.GrantedByUserID,
		&i.Permissions,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProfilePermissionStatus = `-- name: UpdateProfilePermissionStatus :one
UPDATE profile_permissions
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, profile_id, shared_with_user_id, granted_by_user_id, permissions, status, expires_at, created_at, updated_at
`

type UpdateProfilePermissionStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateProfilePermissionStatus(ctx context.Context, arg UpdateProfilePermissionStatusParams) (ProfilePermission, error) {
	row := q.db.QueryRowContext(ctx, updateProfilePermissionStatus, arg.ID, arg.Status)
	var i ProfilePermission
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.SharedWithUserID,
		&i.GrantedByUserID,
		&i.Permissions,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
