// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profiles.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createDoseSchedule = `-- name: CreateDoseSchedule :one

INSERT INTO dose_schedules (
    profile_id,
    name,
    time
) VALUES ($1, $2, $3)
RETURNING id, profile_id, name, time, created_at, updated_at
`

type CreateDoseScheduleParams struct {
	ProfileID uuid.UUID `json:"profile_id"`
	Name      string    `json:"name"`
	Time      time.Time `json:"time"`
}

// Dose Schedule queries
func (q *Queries) CreateDoseSchedule(ctx context.Context, arg CreateDoseScheduleParams) (DoseSchedule, error) {
	row := q.db.QueryRowContext(ctx, createDoseSchedule, arg.ProfileID, arg.Name, arg.Time)
	var i DoseSchedule
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Name,
		&i.Time,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProfile = `-- name: CreateProfile :one

INSERT INTO profiles (
    owner_user_id,
    name,
    date_of_birth,
    timezone
) VALUES ($1, $2, $3, $4)
RETURNING id, owner_user_id, name, date_of_birth, timezone, created_at, updated_at
`

type CreateProfileParams struct {
	OwnerUserID uuid.UUID    `json:"owner_user_id"`
	Name        string       `json:"name"`
	DateOfBirth sql.NullTime `json:"date_of_birth"`
	Timezone    string       `json:"timezone"`
}

// Profile queries
func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, createProfile,
		arg.OwnerUserID,
		arg.Name,
		arg.DateOfBirth,
		arg.Timezone,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.DateOfBirth,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDoseSchedule = `-- name: DeleteDoseSchedule :exec
DELETE FROM dose_schedules WHERE id = $1
`

func (q *Queries) DeleteDoseSchedule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDoseSchedule, id)
	return err
}

const deleteDoseSchedulesByProfile = `-- name: DeleteDoseSchedulesByProfile :exec
DELETE FROM dose_schedules WHERE profile_id = $1
`

func (q *Queries) DeleteDoseSchedulesByProfile(ctx context.Context, profileID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDoseSchedulesByProfile, profileID)
	return err
}

const deleteProfile = `-- name: DeleteProfile :exec
DELETE FROM profiles WHERE id = $1
`

func (q *Queries) DeleteProfile(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteProfile, id)
	return err
}

const getDoseScheduleByID = `-- name: GetDoseScheduleByID :one
SELECT id, profile_id, name, time, created_at, updated_at
FROM dose_schedules
WHERE id = $1
`

func (q *Queries) GetDoseScheduleByID(ctx context.Context, id uuid.UUID) (DoseSchedule, error) {
	row := q.db.QueryRowContext(ctx, getDoseScheduleByID, id)
	var i DoseSchedule
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Name,
		&i.Time,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileByID = `-- name: GetProfileByID :one
SELECT id, owner_user_id, name, date_of_birth, timezone, created_at, updated_at
FROM profiles
WHERE id = $1
`

func (q *Queries) GetProfileByID(ctx context.Context, id uuid.UUID) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getProfileByID, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.DateOfBirth,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDoseSchedulesByProfile = `-- name: ListDoseSchedulesByProfile :many
SELECT id, profile_id, name, time, created_at, updated_at
FROM dose_schedules
WHERE profile_id = $1
ORDER BY time ASC
`

func (q *Queries) ListDoseSchedulesByProfile(ctx context.Context, profileID uuid.UUID) ([]DoseSchedule, error) {
	rows, err := q.db.QueryContext(ctx, listDoseSchedulesByProfile, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DoseSchedule{}
	for rows.Next() {
		var i DoseSchedule
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.Name,
			&i.Time,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfilesByOwner = `-- name: ListProfilesByOwner :many
SELECT id, owner_user_id, name, date_of_birth, timezone, created_at, updated_at
FROM profiles
WHERE owner_user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListProfilesByOwner(ctx context.Context, ownerUserID uuid.UUID) ([]Profile, error) {
	rows, err := q.db.QueryContext(ctx, listProfilesByOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Profile{}
	for rows.Next() {
		var i Profile
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Name,
			&i.DateOfBirth,
			&i.Timezone,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDoseSchedule = `-- name: UpdateDoseSchedule :one
UPDATE dose_schedules
SET name = $2, time = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, profile_id, name, time, created_at, updated_at
`

type UpdateDoseScheduleParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
	Time time.Time `json:"time"`
}

func (q *Queries) UpdateDoseSchedule(ctx context.Context, arg UpdateDoseScheduleParams) (DoseSchedule, error) {
	row := q.db.QueryRowContext(ctx, updateDoseSchedule, arg.ID, arg.Name, arg.Time)
	var i DoseSchedule
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Name,
		&i.Time,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE profiles
SET name = $2, date_of_birth = $3, timezone = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, owner_user_id, name, date_of_birth, timezone, created_at, updated_at
`

type UpdateProfileParams struct {
	ID          uuid.UUID    `json:"id"`
	Name        string       `json:"name"`
	DateOfBirth sql.NullTime `json:"date_of_birth"`
	Timezone    string       `json:"timezone"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error) {
	row := q.db.QueryRowContext(ctx, updateProfile,
		arg.ID,
		arg.Name,
		arg.DateOfBirth,
		arg.Timezone,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.DateOfBirth,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
